### ISSUE TITLE
tryFindResource should not include assembly name

### ISSUE THREAD

**Issue by Shawdooow** [jpbruyere/vke.net#13]
https://github.com/jpbruyere/vke.net/blob/b62f3d293d24c5f79bfeaa7255c6f9e917548e29/vke/src/Utils.cs#L77

**Comment by jpbruyere** [comment]
solved [here](https://github.com/jpbruyere/vke.net/commit/0b83a36de8c63284a8e51fa4ecc5e0a4a16b4414)
