### ISSUE TITLE
GLFW DLL not load

### ISSUE THREAD

**Issue by NaiiThez** [jpbruyere/vke.net#5]
I try to use vke.net. I added vke.net with NuGet and I used your sample code ClearScreen but when I launched I get System.DIINotFound Exception the program cannot load DLL 'glfw3' ?

**Comment by jpbruyere** [comment]
What's your platform? windows 10? have you installed [glfw3](https://www.glfw.org/)?

**Comment by jpbruyere** [comment]
I've update vke to 0.1.21-beta, maybe it will solve the problem with the new glfw-sharp.

**Comment by NaiiThez** [comment]
Thanks you with 0.1.21-beta I don't have the error. Thanks you.
Is it possible to talk with about wrapper in C# with C++ libs ?

**Comment by jpbruyere** [comment]
I'm not sure to understand your question, I guess you ask for C++ wrapper for dotnet. It's possible, but it's less straightforward than accessing pure c code. Have a look [here](https://stackoverflow.com/questions/6332126/call-unmanaged-c-code-from-c-sharp-using-pinvoke) for more infos. I think I can close this issue. Don't hesitate to ask for further informations on vke, it's not yet documented, and new testers questions will give me hints to start documenting.
