### ISSUE TITLE
GetStreamFromPath(string) assumes assembly will not have periods in it

### ISSUE THREAD

**Issue by Shawdooow** [jpbruyere/vke.net#9]
I have an assembly with embedded `.spv` shaders with a name like `engine.module` and this function appears to only check for an assembly called `engine` and gives up once it fails to find it.

https://github.com/jpbruyere/vke.net/blob/0d2872f7c5791dcc6860227dbb34299f2da4340a/vke/src/Utils.cs#L45

**Comment by jpbruyere** [comment]
I've pushed a new beta to nuget with the modification to allow those assembly names with 2 parts. (version 0.2.3-beta).
Be aware that from 0.2.2-beta, vke minimal framework is netcoreapp3.0. I hope this will not be a problem. Tell me if netstandard support would be better for you.

**Comment by Shawdooow** [comment]
Thanks for the fast reply and quick fix. Framework version shouldn't matter for my projects as I am on `net6.0-windows`.

**Comment by jpbruyere** [comment]
Ok, thanks, feel free to send screenshots or share your feeling and experience with this lib.

**Comment by Shawdooow** [comment]
Do you have a slack / discord server?
